#server:
#  port: ${GATEWAY_SERVER_PORT:9003}
#***********************https相关配置********************
server:
  port: 9003
#https:
#  port: 443
#  ssl:
#    key-store: 
#    key-store-password: 
#    key-password: 
#******************************************************
eureka:
  instance:
    hostname: gateway
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
spring:
  security:
    user:
      name: user
      password: password
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
info:
  app:
    name: ${spring.application.name}
    artifactId: '@project.artifactId@'
    version: '@project.version@'
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
zuul:
  retryable: true
  ignoredServices: '*'
  routes:
    authentication:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: authentication
      custom-sensitive-headers: true
    iot-system:
      path: /system/**
      serviceId: iot-system
      sensitiveHeaders:
      custom-sensitive-headers: true
    iot-business:
      path: /business/**
      serviceId: iot-business
      sensitiveHeaders:
