server:
  port: ${REGISTRY_SERVER_PORT:9001}
spring:
  application:
    name: registry
  security:
    user:
      name: user
      password: password
eureka:
  instance:
    hostname: ${REGISTRY_SERVER_IP:127.0.0.1}
    prefer-ip-address: true
    ip-address: ${REGISTRY_SERVER_IP:127.0.0.1}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"      
